project:
  type: website
  output-dir: docs

website:
  page-footer: 
    center: "Copyright 2024, Tipsarp Kittisiam" 
    right: 
      - icon: github
        href: https://github.com/
  search: false
  back-to-top-navigation: true
  navbar:
      left:
        - href: index.qmd
          text: About me
        - href: cv.qmd
          text: Curriculum Vitae
        - text: "Veterinarian Mental Health"
          menu: 
            - href: vet_mh.qmd
              text: Publications and Presentations
            - href: https://minnie-kitt.github.io/vmh-blog/
              text: A Blog About Veterinarian Well-being
      right: 
        - icon: linkedin
          href: https://www.linkedin.com/in/tipsarpk/
        - icon: github
          href: https://github.com/minnie-kitt
        - icon: envelope
          href: mailto:tipsarp.k@gmail.com?cc=tkittisi@uoguelph.ca

format:
  html:
    theme: pulse
    css: styles.css

editor: visual
