project:
  type: website

website:
  page-footer: 
    center: "Copyright 2024, Tipsarp Kittisiam" 
    right: 
      - icon: github
        href: https://github.com/
  search: false
  navbar:
      left:
        - href: index.qmd
          text: Home
        - href: about.qmd
          text: About
        - href: research.qmd
          text: Current Research
        - href: publications.qmd
          text: Past Publications

format:
  html:
    theme: pulse
    css: styles.css

editor: visual
