project:
  type: website
  output-dir: docs

website:
  page-footer: 
    center: "Copyright 2024, Tipsarp Kittisiam" 
    right: 
      - icon: github
        href: https://github.com/
  search: false
  back-to-top-navigation: true
  navbar:
      left:
        - href: index.qmd
          text: About
        - href: cv.qmd
          text: CV
        - text: "Research"
          menu: 
            - href: research.qmd
              text: Current Research
            - href: publications.qmd
              text: Publications        

format:
  html:
    theme: pulse
    css: styles.css

editor: visual
