project:
  type: website
  output-dir: docs

website:
  page-footer: 
    center: "Copyright 2025, Tipsarp Kittisiam" 

  search: false
  back-to-top-navigation: true


format:
  html:
    theme: pulse
    css: styles.css

editor: visual
